openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
  description: This is an example API.
paths:
  /search:
    get:
      summary: Search for items
      description: | 
        Use this endpoint to search for items by keyword.
        
        <form action="/search" method="get">
          <label for="query">Search:</label>
          <input type="text" id="query" name="q">
          <button type="submit">Submit</button>
        </form>
        
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    name:
                      type: string
                      example: Example Item
